/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DtinthProjectHeader {
        "projectIcon": string;
        "projectId": string;
        "projectName": string;
    }
}
declare global {
    interface HTMLDtinthProjectHeaderElement extends Components.DtinthProjectHeader, HTMLStencilElement {
    }
    var HTMLDtinthProjectHeaderElement: {
        prototype: HTMLDtinthProjectHeaderElement;
        new (): HTMLDtinthProjectHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "dtinth-project-header": HTMLDtinthProjectHeaderElement;
    }
}
declare namespace LocalJSX {
    interface DtinthProjectHeader {
        "projectIcon"?: string;
        "projectId"?: string;
        "projectName"?: string;
    }
    interface IntrinsicElements {
        "dtinth-project-header": DtinthProjectHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dtinth-project-header": LocalJSX.DtinthProjectHeader & JSXBase.HTMLAttributes<HTMLDtinthProjectHeaderElement>;
        }
    }
}
